<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SoalTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('soal')->insert(array(
            0 =>
            array(
                'id' => 7,
                'soal' => 'Apakah Anda mengetahui kata “STUNTING” ?',
                'urutan' => 1,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 7,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:27:36',
                'updated_at' => '2022-02-22 02:27:36',
            ),
            1 =>
            array(
                'id' => 8,
                'soal' => 'Dari mana Anda mengetahui STUNTING?',
                'urutan' => 2,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 7,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:28:26',
                'updated_at' => '2022-02-22 02:28:26',
            ),
            2 =>
            array(
                'id' => 9,
                'soal' => 'Apa yang dimaksud dengan Stunting menurut Anda ?',
                'urutan' => 3,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 7,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:28:41',
                'updated_at' => '2022-02-22 02:28:41',
            ),
            3 =>
            array(
                'id' => 10,
                'soal' => 'Apakah ada makanan yang dilarang saat hamil ? sebutkan !',
                'urutan' => 1,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 8,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:29:44',
                'updated_at' => '2022-02-22 02:29:44',
            ),
            4 =>
            array(
                'id' => 11,
                'soal' => 'Apakah dirumah Anda mendahulukan laki-laki makan sebelum perempuan ?',
                'urutan' => 2,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 8,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:30:03',
                'updated_at' => '2022-02-22 02:30:03',
            ),
            5 =>
            array(
                'id' => 12,
                'soal' => 'Apakah Ada Paksaan dalam pernikahan (Kesiapan Menikah)?',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 8,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:30:19',
                'updated_at' => '2022-02-22 02:30:19',
            ),
            6 =>
            array(
                'id' => 13,
                'soal' => 'Jumlah Pendapatan',
                'urutan' => 1,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 9,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:31:31',
                'updated_at' => '2022-02-22 02:31:31',
            ),
            7 =>
            array(
                'id' => 14,
                'soal' => 'Sumber pendapatan (boleh memilih lebih dari 1 pilihan)',
                'urutan' => 2,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 9,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:32:09',
                'updated_at' => '2022-02-22 02:32:09',
            ),
            8 =>
            array(
                'id' => 15,
                'soal' => 'Apakah Anda memilik kartu keluarga sejahtera atau perlindungan sosial ?',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 9,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:32:35',
                'updated_at' => '2022-02-22 02:32:35',
            ),
            9 =>
            array(
                'id' => 16,
                'soal' => 'Sarana air bersih',
                'urutan' => 1,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 10,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:34:28',
                'updated_at' => '2022-02-22 02:34:28',
            ),
            10 =>
            array(
                'id' => 17,
                'soal' => 'Jamban (sarana pembuangan kotoran)',
                'urutan' => 2,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 10,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:35:23',
                'updated_at' => '2022-02-22 02:35:23',
            ),
            11 =>
            array(
                'id' => 18,
                'soal' => 'Jendela kamar tidur',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 10,
                'deleted_at' => NULL,
                'created_at' => '2022-02-22 02:35:50',
                'updated_at' => '2022-02-22 02:35:50',
            ),
            12 =>
            array(
                'id' => 20,
                'soal' => 'Nama Responden',
                'urutan' => 1,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:23:22',
                'updated_at' => '2022-03-01 16:23:22',
            ),
            13 =>
            array(
                'id' => 21,
                'soal' => 'Nomor Telepon/Handphone',
                'urutan' => 2,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:23:59',
                'updated_at' => '2022-03-01 16:23:59',
            ),
            14 =>
            array(
                'id' => 22,
                'soal' => 'Nama Ayah',
                'urutan' => 3,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:24:23',
                'updated_at' => '2022-03-01 16:24:23',
            ),
            15 =>
            array(
                'id' => 23,
                'soal' => 'Pekerjaan Ayah',
                'urutan' => 4,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:24:46',
                'updated_at' => '2022-03-01 16:24:46',
            ),
            16 =>
            array(
                'id' => 24,
                'soal' => 'Nama Ibu',
                'urutan' => 5,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:25:05',
                'updated_at' => '2022-03-01 16:25:05',
            ),
            17 =>
            array(
                'id' => 25,
                'soal' => 'Pekerjaan Ibu',
                'urutan' => 6,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:25:25',
                'updated_at' => '2022-03-01 16:25:25',
            ),
            18 =>
            array(
                'id' => 26,
                'soal' => 'Nama Suami',
                'urutan' => 7,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:25:54',
                'updated_at' => '2022-03-01 16:25:54',
            ),
            19 =>
            array(
                'id' => 27,
                'soal' => 'Pekerjaan Suami',
                'urutan' => 8,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:26:12',
                'updated_at' => '2022-03-01 16:26:12',
            ),
            20 =>
            array(
                'id' => 28,
                'soal' => 'Nama Istri',
                'urutan' => 9,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:26:46',
                'updated_at' => '2022-03-01 16:26:46',
            ),
            21 =>
            array(
                'id' => 29,
                'soal' => 'Pekerjaan Istri',
                'urutan' => 10,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:27:07',
                'updated_at' => '2022-03-01 16:27:19',
            ),
            22 =>
            array(
                'id' => 30,
                'soal' => 'Jenis Kelamin',
                'urutan' => 11,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:27:58',
                'updated_at' => '2022-03-01 16:27:58',
            ),
            23 =>
            array(
                'id' => 31,
                'soal' => 'Umur',
                'urutan' => 12,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:28:33',
                'updated_at' => '2022-03-01 16:28:33',
            ),
            24 =>
            array(
                'id' => 32,
                'soal' => 'Pendidikan Terakhir',
                'urutan' => 13,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:30:34',
                'updated_at' => '2022-03-01 16:30:34',
            ),
            25 =>
            array(
                'id' => 33,
                'soal' => 'Pekerjaan',
                'urutan' => 14,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:30:49',
                'updated_at' => '2022-03-01 16:30:49',
            ),
            26 =>
            array(
                'id' => 34,
                'soal' => 'Usia Menikah Pertama Kali',
                'urutan' => 15,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:31:04',
                'updated_at' => '2022-03-01 16:31:04',
            ),
            27 =>
            array(
                'id' => 35,
                'soal' => 'Usia Saat Hamil Pertama',
                'urutan' => 16,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:31:28',
                'updated_at' => '2022-03-01 16:31:28',
            ),
            28 =>
            array(
                'id' => 36,
                'soal' => 'Jumlah Anak',
                'urutan' => 17,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:31:52',
                'updated_at' => '2022-03-01 16:31:52',
            ),
            29 =>
            array(
                'id' => 38,
                'soal' => 'Usia Hamil Lanjutan > 35 Tahun',
                'urutan' => 18,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:34:53',
                'updated_at' => '2022-03-01 16:34:53',
            ),
            30 =>
            array(
                'id' => 39,
                'soal' => 'Berapa jumlah Anggota keluarga yang tinggal menetap dalam dirumah ?',
                'urutan' => 19,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 11,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:35:33',
                'updated_at' => '2022-03-01 16:36:12',
            ),
            31 =>
            array(
                'id' => 40,
                'soal' => 'Apakah Anda mengetahui kata “STUNTING” ?',
                'urutan' => 1,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:38:23',
                'updated_at' => '2022-03-01 16:38:23',
            ),
            32 =>
            array(
                'id' => 41,
                'soal' => 'Dari mana Anda mengetahui STUNTING?',
                'urutan' => 2,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:39:34',
                'updated_at' => '2022-03-01 16:39:34',
            ),
            33 =>
            array(
                'id' => 42,
                'soal' => 'Apa yang dimaksud dengan Stunting menurut Anda ?',
                'urutan' => 3,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 12,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:41:10',
                'updated_at' => '2022-03-01 16:41:10',
            ),
            34 =>
            array(
                'id' => 43,
                'soal' => 'Apakah ada makanan yang dilarang saat hamil ? sebutkan !',
                'urutan' => 1,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:42:02',
                'updated_at' => '2022-03-01 16:42:02',
            ),
            35 =>
            array(
                'id' => 44,
                'soal' => 'Apakah dirumah Anda mendahulukan laki-laki makan sebelum perempuan ?',
                'urutan' => 2,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:42:28',
                'updated_at' => '2022-03-01 16:42:28',
            ),
            36 =>
            array(
                'id' => 45,
                'soal' => 'Apakah Ada Paksaan dalam pernikahan (Kesiapan Menikah)?',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:42:52',
                'updated_at' => '2022-03-01 16:42:52',
            ),
            37 =>
            array(
                'id' => 46,
                'soal' => 'Apakah Anda Hamil sebelum nikah ?',
                'urutan' => 4,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:43:11',
                'updated_at' => '2022-03-01 16:43:11',
            ),
            38 =>
            array(
                'id' => 47,
                'soal' => 'Jumlah Pendapatan',
                'urutan' => 1,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:45:54',
                'updated_at' => '2022-03-01 16:45:54',
            ),
            39 =>
            array(
                'id' => 48,
                'soal' => 'Sumber pendapatan (boleh memilih lebih dari 1 pilihan)',
                'urutan' => 2,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:47:19',
                'updated_at' => '2022-03-01 16:47:19',
            ),
            40 =>
            array(
                'id' => 49,
                'soal' => 'Apakah Anda memilik kartu keluarga sejahtera atau perlindungan sosial ?',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:47:48',
                'updated_at' => '2022-03-01 16:47:48',
            ),
            41 =>
            array(
                'id' => 50,
                'soal' => 'Pengeluaran keluarga lebih banyak dihabiskan untuk apa?',
                'urutan' => 4,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:49:05',
                'updated_at' => '2022-03-01 16:49:05',
            ),
            42 =>
            array(
                'id' => 51,
                'soal' => 'Apakah keluarga anda Mendapatkan bantuan sosial seperti PKH,PBNT, BST dan lain-lain',
                'urutan' => 5,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 14,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 16:55:24',
                'updated_at' => '2022-03-01 16:55:24',
            ),
            43 =>
            array(
                'id' => 52,
                'soal' => 'Sarana air bersih',
                'urutan' => 1,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:00:56',
                'updated_at' => '2022-03-01 17:00:56',
            ),
            44 =>
            array(
                'id' => 53,
                'soal' => 'Jamban(sarana pembuangankotoran)',
                'urutan' => 2,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:02:20',
                'updated_at' => '2022-03-01 17:02:20',
            ),
            45 =>
            array(
                'id' => 54,
                'soal' => 'Sarana pembuangan air limbah',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:03:00',
                'updated_at' => '2022-03-01 17:03:00',
            ),
            46 =>
            array(
                'id' => 55,
                'soal' => 'Sarana pembuangan sampah (tempat sampah)',
                'urutan' => 4,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:03:37',
                'updated_at' => '2022-03-01 17:03:37',
            ),
            47 =>
            array(
                'id' => 56,
                'soal' => 'Membuang sampah ketempat sampah',
                'urutan' => 5,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:04:13',
                'updated_at' => '2022-03-01 17:04:13',
            ),
            48 =>
            array(
                'id' => 57,
                'soal' => 'Dinding',
                'urutan' => 6,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:04:51',
                'updated_at' => '2022-03-01 17:04:51',
            ),
            49 =>
            array(
                'id' => 58,
                'soal' => 'Lantai',
                'urutan' => 7,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:05:18',
                'updated_at' => '2022-03-01 17:05:18',
            ),
            50 =>
            array(
                'id' => 59,
                'soal' => 'Jendela kamar tidur',
                'urutan' => 8,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:05:39',
                'updated_at' => '2022-03-01 17:05:39',
            ),
            51 =>
            array(
                'id' => 60,
                'soal' => 'Jendela ruang keluarga',
                'urutan' => 9,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:06:15',
                'updated_at' => '2022-03-01 17:06:15',
            ),
            52 =>
            array(
                'id' => 61,
                'soal' => 'Ventilasi',
                'urutan' => 10,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:06:43',
                'updated_at' => '2022-03-01 17:06:43',
            ),
            53 =>
            array(
                'id' => 62,
                'soal' => 'LubangAsapDapur',
                'urutan' => 11,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:07:16',
                'updated_at' => '2022-03-01 17:07:16',
            ),
            54 =>
            array(
                'id' => 63,
                'soal' => 'Pencahayaan',
                'urutan' => 12,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:07:45',
                'updated_at' => '2022-03-01 17:07:45',
            ),
            55 =>
            array(
                'id' => 64,
                'soal' => 'Apa yang digunakan untuk memasak',
                'urutan' => 13,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 15,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:08:28',
                'updated_at' => '2022-03-01 17:08:28',
            ),
            56 =>
            array(
                'id' => 65,
                'soal' => 'Apakah anda tau keluarga anda punya Riwayat penyakit',
                'urutan' => 1,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:10:38',
                'updated_at' => '2022-03-01 17:10:38',
            ),
            57 =>
            array(
                'id' => 66,
                'soal' => 'Apakah anda dan keluarga anda biasanya terkena Paparan asap rokok',
                'urutan' => 2,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:11:08',
                'updated_at' => '2022-03-01 17:11:08',
            ),
            58 =>
            array(
                'id' => 67,
                'soal' => 'Berapa kali keluarga anda mandi dalam sehari',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:11:40',
                'updated_at' => '2022-03-01 17:11:40',
            ),
            59 =>
            array(
                'id' => 68,
                'soal' => 'Berapa kali anda/ keluarga anda Makan Setiap hari',
                'urutan' => 4,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:12:21',
                'updated_at' => '2022-03-01 17:21:26',
            ),
            60 =>
            array(
                'id' => 69,
                'soal' => 'Apakah Anda mengonsumsi suplemen ?',
                'urutan' => 5,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:15:05',
                'updated_at' => '2022-03-01 17:21:42',
            ),
            61 =>
            array(
                'id' => 70,
                'soal' => 'Sudah berapa lama Anda mengonsumsi suplemen ?',
                'urutan' => 6,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:20:43',
                'updated_at' => '2022-03-01 17:21:50',
            ),
            62 =>
            array(
                'id' => 71,
                'soal' => 'Seberapa sering Anda mengonsumsi suplemen makanan?',
                'urutan' => 7,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:23:09',
                'updated_at' => '2022-03-01 17:23:09',
            ),
            63 =>
            array(
                'id' => 72,
                'soal' => 'Apa alasan Anda tidak mengonsumsi suplemen ?',
                'urutan' => 8,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:24:41',
                'updated_at' => '2022-03-01 17:24:41',
            ),
            64 =>
            array(
                'id' => 73,
                'soal' => 'Apa saja yang dimakan tiap hari (perminggu)',
                'urutan' => 9,
                'tipe_jawaban' => 'Kotak Centang',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:25:49',
                'updated_at' => '2022-03-01 17:25:49',
            ),
            65 =>
            array(
                'id' => 74,
                'soal' => 'Remaja: Berapa KEK ... Cm (di isi untuk Kebutuhan anak Remaja saja)',
                'urutan' => 10,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:28:06',
                'updated_at' => '2022-03-01 17:28:45',
            ),
            66 =>
            array(
                'id' => 75,
                'soal' => 'Remaja: BerapaHB ... g/dL (di isi untuk Kebutuhan anak Remaja saja)',
                'urutan' => 11,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:29:52',
                'updated_at' => '2022-03-01 17:29:52',
            ),
            67 =>
            array(
                'id' => 76,
                'soal' => 'Remaja: IMT ... Kg/m2 (di isi untuk Kebutuhan anak Remaja saja)',
                'urutan' => 12,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:30:49',
                'updated_at' => '2022-03-01 17:37:41',
            ),
            68 =>
            array(
                'id' => 77,
                'soal' => 'Remaja: TekananDarah ... mm/Hg (di isi untuk Kebutuhan anak Remaja saja)',
                'urutan' => 13,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:31:20',
                'updated_at' => '2022-03-01 17:37:59',
            ),
            69 =>
            array(
                'id' => 78,
                'soal' => 'Ibu Hamil: Berapa HB ... g/dL (Di isi oleh responden ibu hamil)',
                'urutan' => 14,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:32:09',
                'updated_at' => '2022-03-01 17:34:25',
            ),
            70 =>
            array(
                'id' => 79,
                'soal' => 'Ibu Hamil: Berapa KEK ... Cm (Di isi oleh responden ibu hamil)',
                'urutan' => 15,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:34:53',
                'updated_at' => '2022-03-01 17:38:35',
            ),
            71 =>
            array(
                'id' => 80,
                'soal' => 'Ibu Hamil: Berapa BB ... Kg (Di isi oleh responden ibu hamil)',
                'urutan' => 16,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:35:32',
                'updated_at' => '2022-03-01 17:38:58',
            ),
            72 =>
            array(
                'id' => 81,
                'soal' => 'Ibu Hamil: Tekanan Darah ... mm/Hg (Di isi oleh responden ibu hamil)',
                'urutan' => 17,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:36:11',
                'updated_at' => '2022-03-01 17:39:11',
            ),
            73 =>
            array(
                'id' => 82,
                'soal' => 'Ibu Hamil: Penambahan BB selama hamil ... Kg (Di isi oleh responden ibu hamil)',
                'urutan' => 18,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:36:42',
                'updated_at' => '2022-03-01 17:39:21',
            ),
            74 =>
            array(
                'id' => 83,
                'soal' => 'Ibu Hamil: Rutin Tablet FE ? (Di isi oleh responden ibu hamil)',
                'urutan' => 19,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:37:16',
                'updated_at' => '2022-03-01 17:39:39',
            ),
            75 =>
            array(
                'id' => 85,
                'soal' => 'Ibu Hamil: ANC ? (Di isi oleh responden ibu hamil)',
                'urutan' => 20,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:42:41',
                'updated_at' => '2022-03-01 17:42:41',
            ),
            76 =>
            array(
                'id' => 86,
                'soal' => 'Ibu Hamil: Imunisasi ? (Di isi oleh responden ibu hamil)',
                'urutan' => 21,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:44:14',
                'updated_at' => '2022-03-01 17:44:14',
            ),
            77 =>
            array(
                'id' => 87,
                'soal' => 'Ibu Hamil: KB ? (Di isi oleh responden ibu hamil)',
                'urutan' => 22,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:44:56',
                'updated_at' => '2022-03-01 17:44:56',
            ),
            78 =>
            array(
                'id' => 88,
                'soal' => 'Ibu Hamil: Supelemen tambahan ? (Di isi oleh responden ibu hamil)',
                'urutan' => 23,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:45:44',
                'updated_at' => '2022-03-01 17:45:44',
            ),
            79 =>
            array(
                'id' => 89,
                'soal' => 'Ibu Nifas / Menyusui: Siapa yang menolong ibu saat bersalin ? (di isi ibu Nifas dan Menyusui)',
                'urutan' => 24,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:48:42',
                'updated_at' => '2022-03-01 17:48:42',
            ),
            80 =>
            array(
                'id' => 90,
                'soal' => 'Ibu Nifas / Menyusui: Apakah Ibu akan memberikan ASI eksklusif ? (di isi ibu Nifas dan Menyusui)',
                'urutan' => 25,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:52:36',
                'updated_at' => '2022-03-01 17:54:21',
            ),
            81 =>
            array(
                'id' => 91,
                'soal' => 'Ibu Nifas / Menyusui: Kapan Ibu mulai memberikan ASI pada bayi ? (di isi ibu Nifas dan Menyusui)',
                'urutan' => 26,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:53:44',
                'updated_at' => '2022-03-01 17:53:44',
            ),
            82 =>
            array(
                'id' => 92,
                'soal' => 'Ibu Nifas / Menyusui: Supelemen tambahan ? (di isi ibu Nifas dan Menyusui)',
                'urutan' => 27,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:55:18',
                'updated_at' => '2022-03-01 17:55:18',
            ),
            83 =>
            array(
                'id' => 93,
                'soal' => 'Bayi, Baduta, dan Balita: Berapa PB/U ?',
                'urutan' => 28,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:56:02',
                'updated_at' => '2022-03-01 17:56:02',
            ),
            84 =>
            array(
                'id' => 94,
                'soal' => 'Bayi, Baduta, dan Balita: Berapa TB/U ?',
                'urutan' => 29,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:56:33',
                'updated_at' => '2022-03-01 17:56:33',
            ),
            85 =>
            array(
                'id' => 95,
                'soal' => 'Bayi, Baduta, dan Balita: Berapa BB/U ?',
                'urutan' => 30,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:57:04',
                'updated_at' => '2022-03-01 17:57:04',
            ),
            86 =>
            array(
                'id' => 96,
                'soal' => 'Bayi, Baduta, dan Balita: IMT/U ?',
                'urutan' => 31,
                'tipe_jawaban' => 'Jawaban Singkat',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:57:23',
                'updated_at' => '2022-03-01 17:57:23',
            ),
            87 =>
            array(
                'id' => 97,
                'soal' => 'Bayi, Baduta, dan Balita: Status imunisasi ?',
                'urutan' => 32,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:58:31',
                'updated_at' => '2022-03-01 17:58:31',
            ),
            88 =>
            array(
                'id' => 98,
                'soal' => 'Bayi, Baduta, dan Balita: Suplemen tambahan ?',
                'urutan' => 33,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 17:59:09',
                'updated_at' => '2022-03-01 17:59:09',
            ),
            89 =>
            array(
                'id' => 99,
                'soal' => 'Apakah ibu pernah mendengar istilah “kolostrum”? Apa yang dimaksud dengan kolostrum?',
                'urutan' => 34,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:00:10',
                'updated_at' => '2022-03-01 18:00:10',
            ),
            90 =>
            array(
                'id' => 100,
                'soal' => 'Apakah ibu memberikan kolostrum pada bayi Ibu?',
                'urutan' => 35,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:00:45',
                'updated_at' => '2022-03-01 18:00:45',
            ),
            91 =>
            array(
                'id' => 101,
                'soal' => 'Apakah ibu melaksanakan Inisiasi Menyusui Dini (IMD)?',
                'urutan' => 36,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:01:06',
                'updated_at' => '2022-03-01 18:01:06',
            ),
            92 =>
            array(
                'id' => 102,
                'soal' => 'Setelah bayi lahir, hal apa yang dilakukan ?',
                'urutan' => 37,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:02:10',
                'updated_at' => '2022-03-01 18:02:10',
            ),
            93 =>
            array(
                'id' => 103,
                'soal' => 'Berapa lama ibu melaksanakan Inisiasi Menyusui Dini (IMD)?',
                'urutan' => 38,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:02:42',
                'updated_at' => '2022-03-01 18:02:42',
            ),
            94 =>
            array(
                'id' => 104,
                'soal' => 'Apakah anak ibu diberikan asi ekslusif ?',
                'urutan' => 39,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:03:01',
                'updated_at' => '2022-03-01 18:03:01',
            ),
            95 =>
            array(
                'id' => 105,
                'soal' => 'Apakah anak ibu ASI dua tahun ?',
                'urutan' => 40,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:03:50',
                'updated_at' => '2022-03-01 18:03:50',
            ),
            96 =>
            array(
                'id' => 106,
                'soal' => 'Pemberian makanan tambahan ?',
                'urutan' => 41,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 16,
                'deleted_at' => NULL,
                'created_at' => '2022-03-01 18:04:07',
                'updated_at' => '2022-03-01 18:04:07',
            ),
            97 =>
            array(
                'id' => 107,
                'soal' => 'Apakah dirumah Anda, Anda harus mematuhi peraturan yang dibuat oleh orangtua ?',
                'urutan' => 1,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 01:50:45',
                'updated_at' => '2022-03-02 01:50:45',
            ),
            98 =>
            array(
                'id' => 108,
                'soal' => 'Apakah dirumah Anda Orangtua sering marah kepada Anda ?',
                'urutan' => 2,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:25:42',
                'updated_at' => '2022-03-02 02:25:42',
            ),
            99 =>
            array(
                'id' => 109,
                'soal' => 'Apakah Orangtua sering melakukan kekerasan (cont. Memukul) terhadap Anda ?',
                'urutan' => 3,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:26:01',
                'updated_at' => '2022-03-02 02:26:01',
            ),
            100 =>
            array(
                'id' => 110,
                'soal' => 'Apakah semua keputusan dirumah berada di tangan orangtua Anda ?',
                'urutan' => 4,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:26:21',
                'updated_at' => '2022-03-02 02:26:21',
            ),
            101 =>
            array(
                'id' => 111,
                'soal' => 'Apakah Orangtua jarang menceritakan masalah mereka kepada Anda ?',
                'urutan' => 5,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:26:36',
                'updated_at' => '2022-03-02 02:26:36',
            ),
            102 =>
            array(
                'id' => 112,
                'soal' => 'Apakah memberikan kesempatan untuk mengungkapkan apa yang Anda inginkan ?',
                'urutan' => 6,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:26:55',
                'updated_at' => '2022-03-02 02:26:55',
            ),
            103 =>
            array(
                'id' => 113,
                'soal' => 'Apakah Orangtua sering menjelaskan kepada Anda tentang perbuatan yang baik dan buruk ?',
                'urutan' => 7,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:27:15',
                'updated_at' => '2022-03-02 02:27:15',
            ),
            104 =>
            array(
                'id' => 114,
                'soal' => 'Apakah Orangtua sering bertanya tentang apa yang akan Anda lakukan ?',
                'urutan' => 8,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:27:36',
                'updated_at' => '2022-03-02 02:27:36',
            ),
            105 =>
            array(
                'id' => 115,
                'soal' => 'Apakah Jika Anda berperilaku baik, maka orangtua akan memberikan pujian kepada Anda ?',
                'urutan' => 9,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:27:54',
                'updated_at' => '2022-03-02 02:27:54',
            ),
            106 =>
            array(
                'id' => 116,
                'soal' => 'Jika ada permasalahan dalam keluarga, maka orangtua sering berdiskusi dengan Anda untuk membicarakan masalah tersebut ?',
                'urutan' => 10,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:28:10',
                'updated_at' => '2022-03-02 02:28:10',
            ),
            107 =>
            array(
                'id' => 117,
                'soal' => 'Apakah Orangtua tidak membatasi pergaulan Anda ?',
                'urutan' => 11,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:28:42',
                'updated_at' => '2022-03-02 02:28:42',
            ),
            108 =>
            array(
                'id' => 118,
                'soal' => 'Apakah Orangtua tidak bertanya atau melarang untuk melakukan apa yang Anda inginkan ?',
                'urutan' => 12,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:28:58',
                'updated_at' => '2022-03-02 02:28:58',
            ),
            109 =>
            array(
                'id' => 119,
                'soal' => 'Apakah Orangtua Anda berusaha untuk memenuhi keinginan Anda ?',
                'urutan' => 13,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:29:34',
                'updated_at' => '2022-03-02 02:29:34',
            ),
            110 =>
            array(
                'id' => 120,
                'soal' => 'Apakah Orangtua memberikan Anda kebebasan untuk memilih apa yang ingin Anda lakukan atau kerjakan ?',
                'urutan' => 14,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:29:49',
                'updated_at' => '2022-03-02 02:29:49',
            ),
            111 =>
            array(
                'id' => 121,
                'soal' => 'Apakah Orangtua jarang mengatur urusan Anda ?',
                'urutan' => 15,
                'tipe_jawaban' => 'Pilihan Ganda',
                'kategori_soal_id' => 24,
                'deleted_at' => NULL,
                'created_at' => '2022-03-02 02:30:05',
                'updated_at' => '2022-03-02 02:30:05',
            ),
        ));
    }
}
